spring.application.name=securebank-api

# DataSource — PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/securebank
spring.datasource.username=securebank
spring.datasource.password=securebank
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# JWT
jwt.secret=${JWT_SECRET:change-me-in-production-must-be-at-least-256-bits-long-secret-key}
jwt.expiration-ms=86400000

# Swagger / OpenAPI
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs